import clsx from 'clsx'
import { MessageCircleQuestionMark } from 'lucide-react'
import Image from 'next/image'
import styles from './page.module.css'
import NewMessage from './newMessage'

const MOCK_MESSAGES = [
  {
    role: 'ai',
    content: "I'm thinking of something...",
  },
  {
    role: 'user',
    content: 'Is it a cat?',
  },
  {
    role: 'ai',
    content: "I'm thinking of something...",
  },
  {
    role: 'user',
    content: 'Is it a cat?',
  },
  {
    role: 'ai',
    content: "I'm thinking of something...",
  },
  {
    role: 'user',
    content: 'Is it a cat?',
  },
  {
    role: 'ai',
    content: "I'm thinking of something...",
  },
  {
    role: 'user',
    content: 'Is it a cat?',
  },
  {
    role: 'ai',
    content: "I'm thinking of something...",
  },
  {
    role: 'user',
    content: 'Is it a cat?',
  },
  {
    role: 'ai',
    content: "I'm thinking of something...",
  },
  {
    role: 'user',
    content: 'Is it a cat?',
  },
  {
    role: 'ai',
    content: "I'm thinking of something...",
  },
  {
    role: 'user',
    content: 'Is it a cat?',
  },
]

export default function Home() {
  return (
    <main className={styles.page}>
      <header className={styles.header}>
        <div className={styles.title}>
          <MessageCircleQuestionMark size={36} />
          &nbsp;
          <div>
            <h1>BlurQuest</h1>
            <p className={clsx(styles.description, styles.mobile)}>
              Guess what the AI is thinking of
            </p>
          </div>
        </div>
        <p className={clsx(styles.description, styles.desktop)}>
          Guess what the AI is thinking of
        </p>
      </header>
      <section className={styles.content}>
        <div className={styles.img_container}>
          <div className={styles.img_wrapper}>
            <Image
              alt="Blurred image generated by AI for the guessing challenge"
              className={styles.image}
              height={300}
              src="https://picsum.photos/600"
              style={{
                filter: 'blur(20px)',
              }}
              width={300}
            />
          </div>
        </div>
        <div className={styles.col}>
          <div className={styles.chat}>
            {MOCK_MESSAGES.map((message, index) => (
              <div
                key={index}
                className={clsx(
                  styles.message,
                  message.role === 'ai' ? styles.msg_ai : styles.msg_user,
                )}
              >
                {message.content}
              </div>
            ))}
          </div>
          <NewMessage />
        </div>
      </section>
    </main>
  )
}
