'use client'
import { useChat } from '@ai-sdk/react'
import { UIDataTypes, UIMessage } from 'ai'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Messages from './messages'
import NewMessage from './newMessage'
import styles from './page.module.css'
import { useSpeechSynthesis } from './useSpeechSynthesis'

type UITools = {
  setSecret: {
    input: {
      secret: string
    }
    output: {
      imageUrl: string | null
    }
  }
  finishGame: {
    input: null
    output: {
      finished: true
    }
  }
}

export default function Home() {
  const { messages, sendMessage, status } =
    useChat<UIMessage<unknown, UIDataTypes, UITools>>()

  const [isBlurred, setIsBlurred] = useState(true)
  const [imageUrl, setImageUrl] = useState('')

  const pronounce = useSpeechSynthesis()

  useEffect(() => {
    const lastMsg = messages[messages.length - 1]

    if (lastMsg && lastMsg.role === 'assistant') {
      const setSecret = lastMsg.parts.find((p) => p.type === 'tool-setSecret')
      if (setSecret?.output?.imageUrl) {
        setIsBlurred(true)
        setImageUrl(setSecret.output.imageUrl)
      }

      const finishGame = lastMsg.parts.find((p) => p.type === 'tool-finishGame')
      if (finishGame) {
        setIsBlurred(false)
      }

      pronounce(
        lastMsg.parts
          .filter((p) => p.type === 'text' && p.state === 'done')
          .map((p) => ('text' in p ? p.text : ''))
          .join(' '),
      )
    }
  }, [messages, imageUrl, pronounce])

  useEffect(() => {
    sendMessage({ text: "Let's get started" })
  }, [sendMessage])

  return (
    <>
      <div className={styles.img_container}>
        {imageUrl && (
          <div className={styles.img_wrapper}>
            <Image
              alt="Blurred image generated by AI for the guessing challenge"
              className={styles.image}
              height={300}
              src={imageUrl}
              style={{
                filter: isBlurred ? 'blur(24px)' : 'none',
              }}
              width={300}
              unoptimized
            />
          </div>
        )}
      </div>
      <div className={styles.col}>
        <Messages messages={messages} isPending={status === 'submitted'} />
        <NewMessage sendMessage={sendMessage} />
      </div>
    </>
  )
}
